### ISSUE TITLE
Graphical artifact when Demonic Glove equipped

### ISSUE THREAD

**Issue by InIronClad** [LaughingLeader-DOS2-Mods/WeaponExpansion#1]
Flickering black square occurs when Demonic Glove equipped. Localized specifically to the glove on the character model, size scales up and down based on camera zoom.
![2020-10-06](https://user-images.githubusercontent.com/17327878/95300231-c0724280-0833-11eb-95e4-f19433a937dd.png)
![2020-10-06 (1)](https://user-images.githubusercontent.com/17327878/95300241-c405c980-0833-11eb-902f-840838d63730.png)

**Comment by LaughingLeader** [comment]
Looks like this is a rendering bug with the model's material when bloom is enabled. Not exactly sure why, but I made some adjustments to the opacity blendmode for it and that fixed it.
